CarPooling.Web/Areas/Settings/Controllers/RatingsController.cs
using System.Collections.Generic;
using System.Linq;
using CarPooling.BussinesLogic.Interfaces;
using CarPooling.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace CarPooling.Web.Areas.Settings.Controllers
{
    [Area("Settings")]
    public class RatingsController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRatingService _ratingService;
        public RatingsController(IUserService userService, 
           IRatingService ratingService)
        {
            _userService = userService;
            _ratingService = ratingService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Left()
        {
            var id = _userService.GetUserIdByClaims(HttpContext.User);
            ViewData["Count"] = _ratingService.GetLeftRatings(id).Count;
            return View();
        }
        public PartialViewResult OnGetLeftPartial(int pageIndex = 1, int pageSize = 10, string sort = "default", string search = null)
        {
            var id = _userService.GetUserIdByClaims(HttpContext.User);
            var model = _ratingService.GetLeftRatings(id, sort, search, pageIndex, pageSize);
            ViewData["Count"] = _ratingService.GetNumberOfLeftRatings(id, search);
            return new PartialViewResult
            {
                ViewName = "~/Areas/Settings/Views/Ratings/_Left.cshtml",
                ViewData = new ViewDataDictionary<List<RatingLeftDTO>>(ViewData, model)
            };
        }
        public IActionResult Received()
        {
            return View();
        }
        public PartialViewResult OnGetReceivedPartial(int pageIndex = 1, int pageSize = 10, string sort = "default", string search = null)
        {
            var id = _userService.GetUserIdByClaims(HttpContext.User);
            var model = _ratingService.GetReceivedRatings(id, sort, search, pageIndex, pageSize);
            ViewData["Count"] = _ratingService.GetNumberOfReceivedRatings(id, search);
            return new PartialViewResult
            {
                ViewName = "~/Areas/Settings/Views/Ratings/_Received.cshtml",
                ViewData = new ViewDataDictionary<List<RatingReceivedDTO>>(ViewData, model)
            };
        }
        public PartialViewResult EditRatingPartial(int ratingId)
        {
            var model = _ratingService.GetRaiting(ratingId);
            return new PartialViewResult
            {
                ViewName = "~/Areas/Settings/Views/Ratings/_EditRating.cshtml",
                ViewData = new ViewDataDictionary<RatingDTO>(ViewData, model)
            };
        }
        [HttpPost]
        public IActionResult AddRating(RatingDTO model)
        {
            if (ModelState.IsValid)
            {
                string userId = _userService.GetUserIdByClaims(HttpContext.User);
                _ratingService.AddRatingToRide(model, userId);
                return RedirectToAction("Enroled", "Rides");
            }
            ModelState.AddModelError("", "Rating Add Error");
            return RedirectToAction("Enroled", "Rides");
        }

        public PartialViewResult OnGetRatePartial()
        {
            return new PartialViewResult
            {
                ViewName = "~/Areas/Settings/Views/Ratings/_Rate.cshtml",
            };
        }
        public IActionResult Edit(RatingDTO ratingModel)
        {
             if (ModelState.IsValid)
            {
                _ratingService.EditRating(ratingModel);
                return Ok();
            }

            ModelState.AddModelError("", "Rating Edit error");
            return BadRequest();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _ratingService.DeleteRatingById(id ?? default(int));
            return RedirectToAction("Left");
        }
    }
}

CarPooling.Web/Areas/Settings/Views/Ratings/Left.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "Ratings Offered";
}

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="ride-content">
            <h3><input id="Search" type="text" placeholder="Search" /></h3>
        </div>
        <table class="table table-bordered table-responsive table-hover">
            <thead>
                <tr>
                    <th class="changeToClick" id="SortGeneral">General <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th class="changeToClick" id="SortAccuracy">Accuracy <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th class="changeToClick" id="SortTalkative">Talkative <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th class="changeToClick" id="SortName">To <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody id="Table"></tbody>
        </table>
    </div>
    <div id="EditRatePartial"></div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="~/scripts/PaginateAndSort.js"></script>
    <script>
    $('.changeToClick').css('cursor', 'pointer');
    $('.changeToDefault').css('cursor', 'default');
    </script>

CarPooling.Web/Areas/Settings/Views/Ratings/Received.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "Ratings Received";
}

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="ride-content">
            <h3><input id="Search" type="text" placeholder="Search" /></h3>
        </div>
        <table class="table table-bordered table-responsive table-hover">
            <thead>
                <tr>
                    <th class="changeToClick" id="SortGeneral">General <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th class="changeToClick" id="SortAccuracy">Accuracy <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th class="changeToClick" id="SortTalkative">Talkative <i class="fa fa-sort" aria-hidden="true"></i></th>
                    <th class="changeToClick" id="SortBy">By <i class="fa fa-sort" aria-hidden="true"></i></th>
                </tr>
            </thead>
            <tbody id="Table"></tbody>
        </table>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="~/scripts/PaginateAndSort.js"></script>
    <script>
    $('.changeToClick').css('cursor', 'pointer');
    $('.changeToDefault').css('cursor', 'default');
    </script>

CarPooling.Web/Areas/Settings/Views/Ratings/_EditRating.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CarPooling.DTO.RatingDTO
<div class="modal fade" id="EditRateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div><!-- end .modal-header -->
            <div class="modal-body">
                <form method="post" novalidate autocomplete="off" class="idealforms login" id="EditRatingForm">
                    <div class="log-header">
                        <span class="log-in">Rate Ride</span>
                        <div class="field">
                            <input asp-for="General" placeholder="General">
                            <span asp-validation-for="General" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="Accuracy" placeholder="Accuracy">
                            <span asp-validation-for="Accuracy" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="Talkative" placeholder="Talkative">
                            <span asp-validation-for="Talkative" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="rideId" placeholder="Seats">
                            <span asp-validation-for="rideId" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="Id" />
                        </div>
                        <div class="field buttons">
                            <button type="button" class="btn green-color" id="SaveRating">Save</button>
                            <button type="button" class="close btn red-color">Close</button>
                        </div>
                    </div>
                </form><!-- end .login -->
            </div><!-- end .modal-body -->
        </div><!-- end .modal-content -->
    </div><!-- end .modal-dialog -->
</div><!-- end .modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
<script>
    console.log("dasdadada");
    $('#EditRateModal').modal('show');
    $("#SaveRating").click(function (e) {
        e.preventDefault();
       data = $("#EditRatingForm").serialize();
    $.ajax({
        data:data,
        method: "POST",
        url: "/Settings/Ratings/Edit?",
        success: function () {
            $('#EditRateModal').modal('hide');
            console.log("Succes");
        },
        error:function(err){
            console.log(err);
        }
    })
});
</script>

CarPooling.Web/Areas/Settings/Views/Ratings/_Left.cshtml
@model List<CarPooling.DTO.RatingLeftDTO>
@{
    int? number = ViewData["Count"] as int?;
    int tpages = (int)number / 10;
}
@foreach (var rate in Model)
{
    <tr>
        <td>@rate.General</td>
        <td>@rate.Accuracy</td>
        <td>@rate.Talkative</td>
        <td><a id="profile changeToClick">@rate.LeftFor</a></td>
        <td><button class="btn btn-success" value="@rate.RatingId" id="EditRating @rate.RatingId">Edit</button></td>
        <td><button class="btn btn-danger" value="@rate.RatingId" id="DeleteRating @rate.RatingId">Delete</button></td>
    </tr>
}
<tr>
    <td colspan="5" style="border:hidden">
        <ul class="pagination">
            @for (int i = 1; i <= tpages + 1; i++)
            {
                <li><a class="myPage changeToClick">@i</a></li>
            }
        </ul>
    </td>
</tr>
<script>
    $('.changeToClick').css('cursor', 'pointer');
    $('.changeToDefault').css('cursor', 'default');
</script>
<script src="~/scripts/Pagination.js"></script>
<script src="~/scripts/RateRide.js"></script>
<script src="~/scripts/Profile.js"></script>

CarPooling.Web/Areas/Settings/Views/Ratings/_Rate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CarPooling.DTO.RatingDTO
<div class="modal fade" id="RateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" >&times;</button>
            </div><!-- end .modal-header -->
            <div class="modal-body">
                <form method="post"  novalidate autocomplete="off" class="idealforms login" asp-controller="Ratings" asp-action="AddRating">
                    <div class="log-header">
                        <span class="log-in">Rate Ride</span>
                        <div class="field">
                            <input asp-for="General" placeholder="General">
                            <span asp-validation-for="General" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="Accuracy" placeholder="Accuracy">
                            <span asp-validation-for="Accuracy" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="Talkative" placeholder="Talkative">
                            <span asp-validation-for="Talkative" class="text-danger"></span>
                        </div>
                        <div class="field">
                            <input asp-for="rideId" placeholder="Seats">
                            <span asp-validation-for="rideId" class="text-danger"></span>
                        </div>
                        <div class="field buttons">
                            <button type="submit" class="btn green-color">Add</button>
                            <button type="button" class="close btn red-color">Close</button> 
                        </div>
                    </div>
                </form><!-- end .login -->
            </div><!-- end .modal-body -->
        </div><!-- end .modal-content -->
    </div><!-- end .modal-dialog -->
</div><!-- end .modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

CarPooling.Web/Areas/Settings/Views/Ratings/_Received.cshtml
@model List<CarPooling.DTO.RatingReceivedDTO>
@{
    int? number = ViewData["Count"] as int?;
    int tpages = (int)number / 10;
}
@foreach (var rate in Model)
{
    <tr>
        <td>@rate.General</td>
        <td>@rate.Accuracy</td>
        <td>@rate.Talkative</td>
        <td><a id="profile changeToClick">@rate.ReceivedFrom</a></td>
    </tr>
}
<tr>
    <td colspan="5" style="border:hidden">
        <ul class="pagination">
            @for (int i = 1; i <= tpages + 1; i++)
            {
                <li><a class="myPage changeToClick">@i</a></li>
            }
        </ul>
    </td>
</tr>
<script>
    $('.changeToClick').css('cursor', 'pointer');
    $('.changeToDefault').css('cursor', 'default');
</script>
<script src="~/scripts/Pagination.js"></script>
<script src="~/scripts/Profile.js"></script>