CarPooling.Web/Controllers/SelectRideController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using CarPooling.BussinesLogic.Interfaces;
using CarPooling.DTO;

namespace CarPooling.Web.Controllers
{
    public class SelectRideController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ISelectRideService _selectRidesService;
        private ISession _session => _httpContextAccessor.HttpContext.Session;
        public SelectRideController(IHttpContextAccessor httpContextAccessor,
            ISelectRideService selectRideService)
        {
            _httpContextAccessor = httpContextAccessor;
            _selectRidesService = selectRideService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SelectedRides(SelectRideDTO model)
        {
            _session.SetString("select", JsonConvert.SerializeObject(model));
            return View();
        }
        public PartialViewResult OnGetSelectedRidesPartial(int pageIndex = 1, int pageSize = 10, string sort = "default", string search = null)
        {
            string value = _session.GetString("select");
            var select = JsonConvert.DeserializeObject<SelectRideDTO>(value);
            List<SelectedRidesWithDistanceDTO> query = _selectRidesService.GetSelectedRides(select, sort, search, pageIndex, pageSize);
            ViewData["Count"] = _selectRidesService.GetNumberOfSelectedRides(select, search);
            return new PartialViewResult
            {
                ViewName = "~/Views/SelectRide/_SelectedRides.cshtml",
                ViewData = new ViewDataDictionary<List<SelectedRidesWithDistanceDTO>>(ViewData, query)
            };
        }
    }
}

CarPooling.Web/Views/SelectRide/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CarPooling.DTO.SelectRideDTO
@{
    Layout = "_Layout";
    ViewBag.Title = "Paputka";
}
<!DOCTYPE html>
<body>
    <section class="main-content">
        <div class="container">
            <div class="row" id="SelectedRidesTable">
                <div class="col-sm-12 col-md-12 col-xs-12">
                    <div class="page-sub-title textcenter">
                        <h2>Select Ride</h2>
                        <div class="line"></div>
                    </div><!-- end .page-sub-title -->
                </div><!-- end .col-lg-12 -->
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <div class="page-content add-new-ride">
                        <form novalidate autocomplete="off" class="idealforms add-ride" id="selectRideForm" method="post" action="@Url.Action("SelectedRides", "SelectRide")">
                            <div class="field">
                                <input type="search" id="sourceSearch" placeholder="From?" />
                                <input asp-for="SourceLocationLat" />
                                <span asp-validation-for="SourceLocationLat" class="text-danger"></span>
                                <input asp-for="SourceCity" />
                                <input asp-for="SourceStreet" />
                                <input asp-for="SourceState" />
                                <input asp-for="SourceLocationLng" />
                            </div>
                            <div class="field">
                                <input type="search" id="destinationSearch" placeholder="Where?" />
                                <input asp-for="DestinationLocationLat" />
                                <span asp-validation-for="DestinationLocationLat" class="text-danger"></span>
                                <input asp-for="DestinationCity" />
                                <input asp-for="DestinationStreet" />
                                <input asp-for="DestinationState" />
                                <input asp-for="DestinationLocationLng" />
                            </div>
                            <div class="field">
                                <input asp-for="TravelStartDateTime">
                                <span asp-validation-for="TravelStartDateTime" class="text-danger"></span>

                            </div>
                            <div>
                            </div>
                            <div class="field buttons">
                                <button type="submit" class="btn btn-lg green-color" id="SearchButton">Search</button>
                            </div>
                        </form>
                    </div><!-- end .page-content -->
                </div><!-- end .col-sm-12 -->
                <div class="col-sm-6 col-md-6 col-xs-6">
                    <div id="map"></div>
                </div>
            </div><!-- end .row -->
        </div><!-- end .container -->
    </section><!-- end .main-content -->
    <script type="text/javascript" src="~/scripts/map.js"></script>
    <script src="~/scripts/Account.js"></script>
</body>

CarPooling.Web/Views/SelectRide/SelectedRides.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Paputka";
    Layout = "_Layout";
}
<section class="main-content">
    <div class="container">
        <div class="row">
            <div class="page-content">
                <div class="clearfix"></div>
                <div class="last-rides">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="page-sub-title textcenter">
                            <h2>RIDES</h2>
                            <div class="line"></div>
                        </div><!-- end .page-sub-title -->
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12" id="rides-list">
                        <div>
                            <article>
                                <div class="ride-content">
                                    <h3><input id="Search" type="text" placeholder="Search" /></h3>
                                </div>
                                <div class="container" style="margin-left:-90px">
                                    <ul class="ride-meta">
                                        <li class="ride-date">
                                            <a id="SortDate" class="changeToClick">
                                                <i class="fa fa-calendar"></i>
                                                Date
                                                <i class="fa fa-sort" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                        <li class="ride-people" name="ascending">
                                            <a id="SortSeats" class="changeToClick">
                                                <i class="fa fa-user"></i>
                                                Seats
                                                <i class="fa fa-sort" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a id="SortPrice" name="ascending" class="changeToClick">
                                                <i class="fa fa-money" aria-hidden="true"></i>
                                                Price
                                                <i class="fa fa-sort" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a id="SortSource" name="ascending" class="changeToClick">
                                                <i class="fa fa-road" aria-hidden="true"></i>
                                                Source
                                                <i class="fa fa-sort" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a id="SortDestination" name="ascending" class="changeToClick">
                                                <i class="fa fa-road" aria-hidden="true"></i>
                                                Destination
                                                <i class="fa fa-sort" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </article>
                          <div id="Table"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div><!-- end .col-md-12 col-sm-12 col-xs-12 -->
                </div><!-- end .last-rides -->
            </div>
        </div>
    </div>
</section>
<div id="ModalMoreRead"></div>
<script type="text/javascript" src="~/scripts/MoreInformation.js"></script>
<script src="~/scripts/PaginateAndSort.js"></script>
<script>
    $('.changeToClick').css('cursor', 'pointer');
    $('.changeToDefault').css('cursor', 'default');
</script>

CarPooling.Web/Views/SelectRide/_SelectedRides.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<CarPooling.DTO.SelectedRidesWithDistanceDTO>
@{
        int? number = ViewData["Count"] as int?;
         int tpages = (int)(number - 1) / 10;
}
@foreach (var m in Model)
{
    <article class="ride-box clearfix row">
        <div class="ride-content">
            <h3><a class="changeToDefault">From @m.Source to @m.Destination</a></h3> ride by <a id="profile" class="changeToClick">@m.Username</a>
        </div>
        <ul class="ride-meta">
            <li class="ride-date">
                <a class="changeToDefault">
                    <i class="fa fa-calendar"></i>
                    @m.TravelStartDateTime
                </a>
            </li>
            <li class="ride-people">
                <a class="changeToDefault">
                    <i class="fa fa-user"></i>
                    @m.Seats
                </a>
            </li>
            <li>
                <a class="changeToDefault">
                    <i class="fa fa-money" aria-hidden="true"></i>
                    @m.Price
                </a>
            </li>
            <li>
                <a class="changeToDefault">
                    <i class="fa fa-road" aria-hidden="true"></i>
                    @String.Format("{0:0.0}", m.DistanceFromSource) km
                </a>
            </li>
            <li>
                <a class="changeToDefault">
                    <i class="fa fa-road" aria-hidden="true"></i>
                    @String.Format("{0:0.0}", m.DistanceFromDestination) km
                </a>
            </li>
            <li>
                <a id="read-more @m.Id" class="changeToClick">
                    <i class="fa fa-file"></i>
                    Read more
                </a>
            </li>
        </ul>
    </article>
}
<ul class="pagination">
    @for (int i = 1; i <= tpages + 1; i++)
    {
        <li><a class="myPage changeToClick">@i</a></li>
    }
</ul>
<script type="text/javascript" src="~/scripts/MoreInformation.js"></script>
<script type="text/javascript" src="~/scripts/Subscribe.js"></script>
<script type="text/javascript" src="~/scripts/Pagination.js"></script>
<script type="text/javascript" src="~/scripts/Profile.js"></script>
<script>
    $('.changeToClick').css('cursor', 'pointer');
    $('.changeToDefault').css('cursor', 'default');
</script>